site_name: pandorapsf
site_url: https://pandoramission.github.io/pandora-psf/
docs_dir: docs

nav:
  - Home: README.md
  - PSF API: PSF.md
  - Scene API: Scene.md
  - Example1: example-psf.ipynb
  - Example2: example-scene.ipynb
  - Example3: example-roiscene.ipynb
  - Example4: example-tracescene.ipynb
  
theme:
  name: "material"
  icon:
    logo: material/blur
  features:
    - content.code.copy
    - content.code.annotate 
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

repo_url: https://github.com/pandoramission/pandora-psf
plugins:
  - search
  - include-markdown
  - mkdocs-jupyter:
      execute: false
  - mkdocstrings:
      default_handler: python      
      handlers:
        python:
          paths: [src]
          load_external_modules: true
          options:
            show_source: false
            inherited_members: true
            filters:
              - "!^_"
            heading_level: 2
            sorting: source 
            docstring_style: numpy
            merge_init_into_class: true
            force_inspection: true
            load_external_modules: true
            docstring_sectioning: true
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
